[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cleancore"
version = "1.0.0"
description = "Zero-overhead data observability with row-level immutability"
readme = "README.md"
authors = [{name = "Sidra Saqlain", email = "sidrasaqlain11@gmail.com"}]
license = {text = "MIT"}
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["cleancore*"]